from models.employee import EmployeeBase
from database.database import SessionLocal
from datetime import date

employee = [
    EmployeeBase(
        id=101,
        name="Aarav Sharma",
        role="Software Engineer",
        experience=3,
        salary=275000,
        department="Engineering",
        joining_date=date(2023, 1, 10),
    ),
    EmployeeBase(
        id=102,
        name="Priya Patel",
        role="HR Specialist",
        experience=4,
        salary=260000,
        department="Human Resources",
        joining_date=date(2022, 2, 15),
    ),
    EmployeeBase(
        id=103,
        name="Rohan Verma",
        role="Senior Backend Developer",
        experience=6,
        salary=310000,
        department="Engineering",
        joining_date=date(2020, 3, 20),
    ),
    EmployeeBase(
        id=104,
        name="Sneha Reddy",
        role="UI/UX Designer",
        experience=3,
        salary=245000,
        department="Design",
        joining_date=date(2023, 4, 5),
    ),
    EmployeeBase(
        id=105,
        name="Vikram Malhotra",
        role="Product Manager",
        experience=7,
        salary=350000,
        department="Product",
        joining_date=date(2019, 5, 12),
    ),
    EmployeeBase(
        id=106,
        name="Ananya Iyer",
        role="Data Scientist",
        experience=4,
        salary=290000,
        department="Data Science",
        joining_date=date(2022, 6, 18),
    ),
    EmployeeBase(
        id=107,
        name="Karan Singh",
        role="DevOps Engineer",
        experience=5,
        salary=305000,
        department="Infrastructure",
        joining_date=date(2021, 7, 22),
    ),
    EmployeeBase(
        id=108,
        name="Neha Gupta",
        role="Financial Analyst",
        experience=4,
        salary=255000,
        department="Finance",
        joining_date=date(2022, 8, 10),
    ),
    EmployeeBase(
        id=109,
        name="Aditya Joshi",
        role="Frontend Developer",
        experience=3,
        salary=240000,
        department="Engineering",
        joining_date=date(2024, 1, 8),
    ),
    EmployeeBase(
        id=110,
        name="Meera Nair",
        role="QA Engineer",
        experience=3,
        salary=250000,
        department="Quality Assurance",
        joining_date=date(2023, 2, 14),
    ),
    EmployeeBase(
        id=111,
        name="Siddharth Rao",
        role="Marketing Specialist",
        experience=4,
        salary=265000,
        department="Marketing",
        joining_date=date(2022, 3, 11),
    ),
    EmployeeBase(
        id=112,
        name="Pooja Das",
        role="Accountant",
        experience=5,
        salary=270000,
        department="Finance",
        joining_date=date(2021, 4, 19),
    ),
    EmployeeBase(
        id=113,
        name="Rahul Deshmukh",
        role="Sales Executive",
        experience=3,
        salary=235000,
        department="Sales",
        joining_date=date(2023, 5, 7),
    ),
    EmployeeBase(
        id=114,
        name="Divya Kapoor",
        role="HR Manager",
        experience=8,
        salary=320000,
        department="Human Resources",
        joining_date=date(2018, 6, 21),
    ),
    EmployeeBase(
        id=115,
        name="Arjun Mehta",
        role="Cloud Architect",
        experience=9,
        salary=400000,
        department="Infrastructure",
        joining_date=date(2018, 7, 13),
    ),
    EmployeeBase(
        id=116,
        name="Kavita Pillai",
        role="Content Strategist",
        experience=3,
        salary=240000,
        department="Marketing",
        joining_date=date(2023, 8, 9),
    ),
    EmployeeBase(
        id=117,
        name="Manish Tiwari",
        role="Customer Support Lead",
        experience=5,
        salary=250000,
        department="Support",
        joining_date=date(2021, 9, 17),
    ),
    EmployeeBase(
        id=118,
        name="Tanvi Saxena",
        role="Security Engineer",
        experience=4,
        salary=300000,
        department="Security",
        joining_date=date(2022, 10, 25),
    ),
    EmployeeBase(
        id=119,
        name="Varun Nambiar",
        role="Business Analyst",
        experience=3,
        salary=275000,
        department="Product",
        joining_date=date(2023, 11, 6),
    ),
    EmployeeBase(
        id=120,
        name="Ishaan Kulkarni",
        role="Mobile App Developer",
        experience=4,
        salary=285000,
        department="Engineering",
        joining_date=date(2022, 12, 12),
    ),
]

with SessionLocal() as session:
    session.add_all(employee)
    session.commit()

print(f"20 Employees Records Created Successfully")
