[project]
name = "fastapi-learning-docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kumar nallana", email = "sasikumarnallana956@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "psycopg[binary]>=3.3.6",
    "pwdlib[argon2]>=0.3.1",
    "python-dotenv>=1.2.4",
    "sqlalchemy>=2.1.3",
]

[project.scripts]
fastapi-learning-docs = "fastapi_learning_docs:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
